// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package instance

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wawilow/pulumi-bytebase/sdk/go/bytebase/internal"
)

// The instance data source list.
func GetList(ctx *pulumi.Context, args *GetListArgs, opts ...pulumi.InvokeOption) (*GetListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetListResult
	err := ctx.Invoke("bytebase:Instance/getList:getList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getList.
type GetListArgs struct {
	// Filter instances by engines.
	Engines []string `pulumi:"engines"`
	// The environment full name. Filter instances by environment.
	Environment *string `pulumi:"environment"`
	// Filter instances by host.
	Host *string `pulumi:"host"`
	// Filter instances by port.
	Port *string `pulumi:"port"`
	// The project full name. Filter instances by project.
	Project *string `pulumi:"project"`
	// Filter instances by name or resource id with wildcard
	Query *string `pulumi:"query"`
	// Filter instances by state. Default ACTIVE.
	State *string `pulumi:"state"`
}

// A collection of values returned by getList.
type GetListResult struct {
	// Filter instances by engines.
	Engines []string `pulumi:"engines"`
	// The environment full name. Filter instances by environment.
	Environment *string `pulumi:"environment"`
	// Filter instances by host.
	Host *string `pulumi:"host"`
	// The provider-assigned unique ID for this managed resource.
	Id        string            `pulumi:"id"`
	Instances []GetListInstance `pulumi:"instances"`
	// Filter instances by port.
	Port *string `pulumi:"port"`
	// The project full name. Filter instances by project.
	Project *string `pulumi:"project"`
	// Filter instances by name or resource id with wildcard
	Query *string `pulumi:"query"`
	// Filter instances by state. Default ACTIVE.
	State *string `pulumi:"state"`
}

func GetListOutput(ctx *pulumi.Context, args GetListOutputArgs, opts ...pulumi.InvokeOption) GetListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetListResultOutput, error) {
			args := v.(GetListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("bytebase:Instance/getList:getList", args, GetListResultOutput{}, options).(GetListResultOutput), nil
		}).(GetListResultOutput)
}

// A collection of arguments for invoking getList.
type GetListOutputArgs struct {
	// Filter instances by engines.
	Engines pulumi.StringArrayInput `pulumi:"engines"`
	// The environment full name. Filter instances by environment.
	Environment pulumi.StringPtrInput `pulumi:"environment"`
	// Filter instances by host.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// Filter instances by port.
	Port pulumi.StringPtrInput `pulumi:"port"`
	// The project full name. Filter instances by project.
	Project pulumi.StringPtrInput `pulumi:"project"`
	// Filter instances by name or resource id with wildcard
	Query pulumi.StringPtrInput `pulumi:"query"`
	// Filter instances by state. Default ACTIVE.
	State pulumi.StringPtrInput `pulumi:"state"`
}

func (GetListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListArgs)(nil)).Elem()
}

// A collection of values returned by getList.
type GetListResultOutput struct{ *pulumi.OutputState }

func (GetListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListResult)(nil)).Elem()
}

func (o GetListResultOutput) ToGetListResultOutput() GetListResultOutput {
	return o
}

func (o GetListResultOutput) ToGetListResultOutputWithContext(ctx context.Context) GetListResultOutput {
	return o
}

// Filter instances by engines.
func (o GetListResultOutput) Engines() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetListResult) []string { return v.Engines }).(pulumi.StringArrayOutput)
}

// The environment full name. Filter instances by environment.
func (o GetListResultOutput) Environment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetListResult) *string { return v.Environment }).(pulumi.StringPtrOutput)
}

// Filter instances by host.
func (o GetListResultOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetListResult) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetListResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetListResultOutput) Instances() GetListInstanceArrayOutput {
	return o.ApplyT(func(v GetListResult) []GetListInstance { return v.Instances }).(GetListInstanceArrayOutput)
}

// Filter instances by port.
func (o GetListResultOutput) Port() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetListResult) *string { return v.Port }).(pulumi.StringPtrOutput)
}

// The project full name. Filter instances by project.
func (o GetListResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetListResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

// Filter instances by name or resource id with wildcard
func (o GetListResultOutput) Query() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetListResult) *string { return v.Query }).(pulumi.StringPtrOutput)
}

// Filter instances by state. Default ACTIVE.
func (o GetListResultOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetListResult) *string { return v.State }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetListResultOutput{})
}
