// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package instance

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wawilow/pulumi-bytebase/sdk/go/bytebase/internal"
)

var _ = internal.GetEnvOrDefault

type GetListInstance struct {
	// Whether assign license for this instance or not.
	Activation  bool                        `pulumi:"activation"`
	DataSources []GetListInstanceDataSource `pulumi:"dataSources"`
	// The instance engine. Support MYSQL, POSTGRES, TIDB, SNOWFLAKE, CLICKHOUSE, MONGODB, SQLITE, REDIS, ORACLE, SPANNER, MSSQL, REDSHIFT, MARIADB, OCEANBASE, COCKROACHDB.
	Engine string `pulumi:"engine"`
	// The engine version.
	EngineVersion string `pulumi:"engineVersion"`
	// The environment name for your instance in "environments/{resource id}" format.
	Environment string `pulumi:"environment"`
	// The external console URL managing this instance (e.g. AWS RDS console, your in-house DB instance console)
	ExternalLink string `pulumi:"externalLink"`
	// The maximum number of connections. The default value is 10.
	MaximumConnections int `pulumi:"maximumConnections"`
	// The instance full name in instances/{resource id} format.
	Name string `pulumi:"name"`
	// The instance unique resource id.
	ResourceId string `pulumi:"resourceId"`
	// How often the instance is synced in seconds. Default 0, means never sync.
	SyncInterval int `pulumi:"syncInterval"`
	// The instance title.
	Title string `pulumi:"title"`
}

// GetListInstanceInput is an input type that accepts GetListInstanceArgs and GetListInstanceOutput values.
// You can construct a concrete instance of `GetListInstanceInput` via:
//
//	GetListInstanceArgs{...}
type GetListInstanceInput interface {
	pulumi.Input

	ToGetListInstanceOutput() GetListInstanceOutput
	ToGetListInstanceOutputWithContext(context.Context) GetListInstanceOutput
}

type GetListInstanceArgs struct {
	// Whether assign license for this instance or not.
	Activation  pulumi.BoolInput                    `pulumi:"activation"`
	DataSources GetListInstanceDataSourceArrayInput `pulumi:"dataSources"`
	// The instance engine. Support MYSQL, POSTGRES, TIDB, SNOWFLAKE, CLICKHOUSE, MONGODB, SQLITE, REDIS, ORACLE, SPANNER, MSSQL, REDSHIFT, MARIADB, OCEANBASE, COCKROACHDB.
	Engine pulumi.StringInput `pulumi:"engine"`
	// The engine version.
	EngineVersion pulumi.StringInput `pulumi:"engineVersion"`
	// The environment name for your instance in "environments/{resource id}" format.
	Environment pulumi.StringInput `pulumi:"environment"`
	// The external console URL managing this instance (e.g. AWS RDS console, your in-house DB instance console)
	ExternalLink pulumi.StringInput `pulumi:"externalLink"`
	// The maximum number of connections. The default value is 10.
	MaximumConnections pulumi.IntInput `pulumi:"maximumConnections"`
	// The instance full name in instances/{resource id} format.
	Name pulumi.StringInput `pulumi:"name"`
	// The instance unique resource id.
	ResourceId pulumi.StringInput `pulumi:"resourceId"`
	// How often the instance is synced in seconds. Default 0, means never sync.
	SyncInterval pulumi.IntInput `pulumi:"syncInterval"`
	// The instance title.
	Title pulumi.StringInput `pulumi:"title"`
}

func (GetListInstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstance)(nil)).Elem()
}

func (i GetListInstanceArgs) ToGetListInstanceOutput() GetListInstanceOutput {
	return i.ToGetListInstanceOutputWithContext(context.Background())
}

func (i GetListInstanceArgs) ToGetListInstanceOutputWithContext(ctx context.Context) GetListInstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceOutput)
}

// GetListInstanceArrayInput is an input type that accepts GetListInstanceArray and GetListInstanceArrayOutput values.
// You can construct a concrete instance of `GetListInstanceArrayInput` via:
//
//	GetListInstanceArray{ GetListInstanceArgs{...} }
type GetListInstanceArrayInput interface {
	pulumi.Input

	ToGetListInstanceArrayOutput() GetListInstanceArrayOutput
	ToGetListInstanceArrayOutputWithContext(context.Context) GetListInstanceArrayOutput
}

type GetListInstanceArray []GetListInstanceInput

func (GetListInstanceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstance)(nil)).Elem()
}

func (i GetListInstanceArray) ToGetListInstanceArrayOutput() GetListInstanceArrayOutput {
	return i.ToGetListInstanceArrayOutputWithContext(context.Background())
}

func (i GetListInstanceArray) ToGetListInstanceArrayOutputWithContext(ctx context.Context) GetListInstanceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceArrayOutput)
}

type GetListInstanceOutput struct{ *pulumi.OutputState }

func (GetListInstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstance)(nil)).Elem()
}

func (o GetListInstanceOutput) ToGetListInstanceOutput() GetListInstanceOutput {
	return o
}

func (o GetListInstanceOutput) ToGetListInstanceOutputWithContext(ctx context.Context) GetListInstanceOutput {
	return o
}

// Whether assign license for this instance or not.
func (o GetListInstanceOutput) Activation() pulumi.BoolOutput {
	return o.ApplyT(func(v GetListInstance) bool { return v.Activation }).(pulumi.BoolOutput)
}

func (o GetListInstanceOutput) DataSources() GetListInstanceDataSourceArrayOutput {
	return o.ApplyT(func(v GetListInstance) []GetListInstanceDataSource { return v.DataSources }).(GetListInstanceDataSourceArrayOutput)
}

// The instance engine. Support MYSQL, POSTGRES, TIDB, SNOWFLAKE, CLICKHOUSE, MONGODB, SQLITE, REDIS, ORACLE, SPANNER, MSSQL, REDSHIFT, MARIADB, OCEANBASE, COCKROACHDB.
func (o GetListInstanceOutput) Engine() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.Engine }).(pulumi.StringOutput)
}

// The engine version.
func (o GetListInstanceOutput) EngineVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.EngineVersion }).(pulumi.StringOutput)
}

// The environment name for your instance in "environments/{resource id}" format.
func (o GetListInstanceOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.Environment }).(pulumi.StringOutput)
}

// The external console URL managing this instance (e.g. AWS RDS console, your in-house DB instance console)
func (o GetListInstanceOutput) ExternalLink() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.ExternalLink }).(pulumi.StringOutput)
}

// The maximum number of connections. The default value is 10.
func (o GetListInstanceOutput) MaximumConnections() pulumi.IntOutput {
	return o.ApplyT(func(v GetListInstance) int { return v.MaximumConnections }).(pulumi.IntOutput)
}

// The instance full name in instances/{resource id} format.
func (o GetListInstanceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.Name }).(pulumi.StringOutput)
}

// The instance unique resource id.
func (o GetListInstanceOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.ResourceId }).(pulumi.StringOutput)
}

// How often the instance is synced in seconds. Default 0, means never sync.
func (o GetListInstanceOutput) SyncInterval() pulumi.IntOutput {
	return o.ApplyT(func(v GetListInstance) int { return v.SyncInterval }).(pulumi.IntOutput)
}

// The instance title.
func (o GetListInstanceOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstance) string { return v.Title }).(pulumi.StringOutput)
}

type GetListInstanceArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstance)(nil)).Elem()
}

func (o GetListInstanceArrayOutput) ToGetListInstanceArrayOutput() GetListInstanceArrayOutput {
	return o
}

func (o GetListInstanceArrayOutput) ToGetListInstanceArrayOutputWithContext(ctx context.Context) GetListInstanceArrayOutput {
	return o
}

func (o GetListInstanceArrayOutput) Index(i pulumi.IntInput) GetListInstanceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstance {
		return vs[0].([]GetListInstance)[vs[1].(int)]
	}).(GetListInstanceOutput)
}

type GetListInstanceDataSource struct {
	// The database for the instance, you can set this if the engine type is POSTGRES.
	Database string `pulumi:"database"`
	// The external secret to get the database password. Learn more: https://www.bytebase.com/docs/get-started/instance/#use-external-secret-manager
	ExternalSecrets []GetListInstanceDataSourceExternalSecret `pulumi:"externalSecrets"`
	// Host or socket for your instance, or the account name if the instance type is Snowflake.
	Host string `pulumi:"host"`
	// The unique data source id in this instance.
	Id string `pulumi:"id"`
	// The connection user password used by Bytebase to perform DDL and DML operations.
	Password string `pulumi:"password"`
	// The port for your instance.
	Port string `pulumi:"port"`
	// The CA certificate. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
	SslCa string `pulumi:"sslCa"`
	// The client certificate. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
	SslCert string `pulumi:"sslCert"`
	// The client key. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
	SslKey string `pulumi:"sslKey"`
	// The data source type. Should be ADMIN or READ_ONLY.
	Type string `pulumi:"type"`
	// Enable SSL connection. Required to use SSL certificates.
	UseSsl bool `pulumi:"useSsl"`
	// The connection user name used by Bytebase to perform DDL and DML operations.
	Username string `pulumi:"username"`
}

// GetListInstanceDataSourceInput is an input type that accepts GetListInstanceDataSourceArgs and GetListInstanceDataSourceOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceInput` via:
//
//	GetListInstanceDataSourceArgs{...}
type GetListInstanceDataSourceInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceOutput() GetListInstanceDataSourceOutput
	ToGetListInstanceDataSourceOutputWithContext(context.Context) GetListInstanceDataSourceOutput
}

type GetListInstanceDataSourceArgs struct {
	// The database for the instance, you can set this if the engine type is POSTGRES.
	Database pulumi.StringInput `pulumi:"database"`
	// The external secret to get the database password. Learn more: https://www.bytebase.com/docs/get-started/instance/#use-external-secret-manager
	ExternalSecrets GetListInstanceDataSourceExternalSecretArrayInput `pulumi:"externalSecrets"`
	// Host or socket for your instance, or the account name if the instance type is Snowflake.
	Host pulumi.StringInput `pulumi:"host"`
	// The unique data source id in this instance.
	Id pulumi.StringInput `pulumi:"id"`
	// The connection user password used by Bytebase to perform DDL and DML operations.
	Password pulumi.StringInput `pulumi:"password"`
	// The port for your instance.
	Port pulumi.StringInput `pulumi:"port"`
	// The CA certificate. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
	SslCa pulumi.StringInput `pulumi:"sslCa"`
	// The client certificate. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
	SslCert pulumi.StringInput `pulumi:"sslCert"`
	// The client key. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
	SslKey pulumi.StringInput `pulumi:"sslKey"`
	// The data source type. Should be ADMIN or READ_ONLY.
	Type pulumi.StringInput `pulumi:"type"`
	// Enable SSL connection. Required to use SSL certificates.
	UseSsl pulumi.BoolInput `pulumi:"useSsl"`
	// The connection user name used by Bytebase to perform DDL and DML operations.
	Username pulumi.StringInput `pulumi:"username"`
}

func (GetListInstanceDataSourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSource)(nil)).Elem()
}

func (i GetListInstanceDataSourceArgs) ToGetListInstanceDataSourceOutput() GetListInstanceDataSourceOutput {
	return i.ToGetListInstanceDataSourceOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceArgs) ToGetListInstanceDataSourceOutputWithContext(ctx context.Context) GetListInstanceDataSourceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceOutput)
}

// GetListInstanceDataSourceArrayInput is an input type that accepts GetListInstanceDataSourceArray and GetListInstanceDataSourceArrayOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceArrayInput` via:
//
//	GetListInstanceDataSourceArray{ GetListInstanceDataSourceArgs{...} }
type GetListInstanceDataSourceArrayInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceArrayOutput() GetListInstanceDataSourceArrayOutput
	ToGetListInstanceDataSourceArrayOutputWithContext(context.Context) GetListInstanceDataSourceArrayOutput
}

type GetListInstanceDataSourceArray []GetListInstanceDataSourceInput

func (GetListInstanceDataSourceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSource)(nil)).Elem()
}

func (i GetListInstanceDataSourceArray) ToGetListInstanceDataSourceArrayOutput() GetListInstanceDataSourceArrayOutput {
	return i.ToGetListInstanceDataSourceArrayOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceArray) ToGetListInstanceDataSourceArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceArrayOutput)
}

type GetListInstanceDataSourceOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSource)(nil)).Elem()
}

func (o GetListInstanceDataSourceOutput) ToGetListInstanceDataSourceOutput() GetListInstanceDataSourceOutput {
	return o
}

func (o GetListInstanceDataSourceOutput) ToGetListInstanceDataSourceOutputWithContext(ctx context.Context) GetListInstanceDataSourceOutput {
	return o
}

// The database for the instance, you can set this if the engine type is POSTGRES.
func (o GetListInstanceDataSourceOutput) Database() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Database }).(pulumi.StringOutput)
}

// The external secret to get the database password. Learn more: https://www.bytebase.com/docs/get-started/instance/#use-external-secret-manager
func (o GetListInstanceDataSourceOutput) ExternalSecrets() GetListInstanceDataSourceExternalSecretArrayOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) []GetListInstanceDataSourceExternalSecret { return v.ExternalSecrets }).(GetListInstanceDataSourceExternalSecretArrayOutput)
}

// Host or socket for your instance, or the account name if the instance type is Snowflake.
func (o GetListInstanceDataSourceOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Host }).(pulumi.StringOutput)
}

// The unique data source id in this instance.
func (o GetListInstanceDataSourceOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Id }).(pulumi.StringOutput)
}

// The connection user password used by Bytebase to perform DDL and DML operations.
func (o GetListInstanceDataSourceOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Password }).(pulumi.StringOutput)
}

// The port for your instance.
func (o GetListInstanceDataSourceOutput) Port() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Port }).(pulumi.StringOutput)
}

// The CA certificate. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
func (o GetListInstanceDataSourceOutput) SslCa() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.SslCa }).(pulumi.StringOutput)
}

// The client certificate. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
func (o GetListInstanceDataSourceOutput) SslCert() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.SslCert }).(pulumi.StringOutput)
}

// The client key. Optional, you can set this if the engine type is MYSQL, POSTGRES, TIDB, CLICKHOUSE or COCKROACHDB.
func (o GetListInstanceDataSourceOutput) SslKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.SslKey }).(pulumi.StringOutput)
}

// The data source type. Should be ADMIN or READ_ONLY.
func (o GetListInstanceDataSourceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Type }).(pulumi.StringOutput)
}

// Enable SSL connection. Required to use SSL certificates.
func (o GetListInstanceDataSourceOutput) UseSsl() pulumi.BoolOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) bool { return v.UseSsl }).(pulumi.BoolOutput)
}

// The connection user name used by Bytebase to perform DDL and DML operations.
func (o GetListInstanceDataSourceOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSource) string { return v.Username }).(pulumi.StringOutput)
}

type GetListInstanceDataSourceArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSource)(nil)).Elem()
}

func (o GetListInstanceDataSourceArrayOutput) ToGetListInstanceDataSourceArrayOutput() GetListInstanceDataSourceArrayOutput {
	return o
}

func (o GetListInstanceDataSourceArrayOutput) ToGetListInstanceDataSourceArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceArrayOutput {
	return o
}

func (o GetListInstanceDataSourceArrayOutput) Index(i pulumi.IntInput) GetListInstanceDataSourceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstanceDataSource {
		return vs[0].([]GetListInstanceDataSource)[vs[1].(int)]
	}).(GetListInstanceDataSourceOutput)
}

type GetListInstanceDataSourceExternalSecret struct {
	// The AWS Secrets Manager to get the database password. Reference doc https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html
	AwsSecretsManagers []GetListInstanceDataSourceExternalSecretAwsSecretsManager `pulumi:"awsSecretsManagers"`
	// The GCP Secret Manager to get the database password. Reference doc https://cloud.google.com/secret-manager/docs
	GcpSecretManagers []GetListInstanceDataSourceExternalSecretGcpSecretManager `pulumi:"gcpSecretManagers"`
	Vaults            []GetListInstanceDataSourceExternalSecretVault            `pulumi:"vaults"`
}

// GetListInstanceDataSourceExternalSecretInput is an input type that accepts GetListInstanceDataSourceExternalSecretArgs and GetListInstanceDataSourceExternalSecretOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretInput` via:
//
//	GetListInstanceDataSourceExternalSecretArgs{...}
type GetListInstanceDataSourceExternalSecretInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretOutput() GetListInstanceDataSourceExternalSecretOutput
	ToGetListInstanceDataSourceExternalSecretOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretOutput
}

type GetListInstanceDataSourceExternalSecretArgs struct {
	// The AWS Secrets Manager to get the database password. Reference doc https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html
	AwsSecretsManagers GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayInput `pulumi:"awsSecretsManagers"`
	// The GCP Secret Manager to get the database password. Reference doc https://cloud.google.com/secret-manager/docs
	GcpSecretManagers GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayInput `pulumi:"gcpSecretManagers"`
	Vaults            GetListInstanceDataSourceExternalSecretVaultArrayInput            `pulumi:"vaults"`
}

func (GetListInstanceDataSourceExternalSecretArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecret)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretArgs) ToGetListInstanceDataSourceExternalSecretOutput() GetListInstanceDataSourceExternalSecretOutput {
	return i.ToGetListInstanceDataSourceExternalSecretOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretArgs) ToGetListInstanceDataSourceExternalSecretOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretOutput)
}

// GetListInstanceDataSourceExternalSecretArrayInput is an input type that accepts GetListInstanceDataSourceExternalSecretArray and GetListInstanceDataSourceExternalSecretArrayOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretArrayInput` via:
//
//	GetListInstanceDataSourceExternalSecretArray{ GetListInstanceDataSourceExternalSecretArgs{...} }
type GetListInstanceDataSourceExternalSecretArrayInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretArrayOutput() GetListInstanceDataSourceExternalSecretArrayOutput
	ToGetListInstanceDataSourceExternalSecretArrayOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretArrayOutput
}

type GetListInstanceDataSourceExternalSecretArray []GetListInstanceDataSourceExternalSecretInput

func (GetListInstanceDataSourceExternalSecretArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecret)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretArray) ToGetListInstanceDataSourceExternalSecretArrayOutput() GetListInstanceDataSourceExternalSecretArrayOutput {
	return i.ToGetListInstanceDataSourceExternalSecretArrayOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretArray) ToGetListInstanceDataSourceExternalSecretArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretArrayOutput)
}

type GetListInstanceDataSourceExternalSecretOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecret)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretOutput) ToGetListInstanceDataSourceExternalSecretOutput() GetListInstanceDataSourceExternalSecretOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretOutput) ToGetListInstanceDataSourceExternalSecretOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretOutput {
	return o
}

// The AWS Secrets Manager to get the database password. Reference doc https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html
func (o GetListInstanceDataSourceExternalSecretOutput) AwsSecretsManagers() GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecret) []GetListInstanceDataSourceExternalSecretAwsSecretsManager {
		return v.AwsSecretsManagers
	}).(GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput)
}

// The GCP Secret Manager to get the database password. Reference doc https://cloud.google.com/secret-manager/docs
func (o GetListInstanceDataSourceExternalSecretOutput) GcpSecretManagers() GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecret) []GetListInstanceDataSourceExternalSecretGcpSecretManager {
		return v.GcpSecretManagers
	}).(GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput)
}

func (o GetListInstanceDataSourceExternalSecretOutput) Vaults() GetListInstanceDataSourceExternalSecretVaultArrayOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecret) []GetListInstanceDataSourceExternalSecretVault {
		return v.Vaults
	}).(GetListInstanceDataSourceExternalSecretVaultArrayOutput)
}

type GetListInstanceDataSourceExternalSecretArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecret)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretArrayOutput) ToGetListInstanceDataSourceExternalSecretArrayOutput() GetListInstanceDataSourceExternalSecretArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretArrayOutput) ToGetListInstanceDataSourceExternalSecretArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretArrayOutput) Index(i pulumi.IntInput) GetListInstanceDataSourceExternalSecretOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstanceDataSourceExternalSecret {
		return vs[0].([]GetListInstanceDataSourceExternalSecret)[vs[1].(int)]
	}).(GetListInstanceDataSourceExternalSecretOutput)
}

type GetListInstanceDataSourceExternalSecretAwsSecretsManager struct {
	// The key name for the password.
	PasswordKeyName string `pulumi:"passwordKeyName"`
	// The secret name to store the password.
	SecretName string `pulumi:"secretName"`
}

// GetListInstanceDataSourceExternalSecretAwsSecretsManagerInput is an input type that accepts GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs and GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretAwsSecretsManagerInput` via:
//
//	GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs{...}
type GetListInstanceDataSourceExternalSecretAwsSecretsManagerInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput() GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput
	ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput
}

type GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs struct {
	// The key name for the password.
	PasswordKeyName pulumi.StringInput `pulumi:"passwordKeyName"`
	// The secret name to store the password.
	SecretName pulumi.StringInput `pulumi:"secretName"`
}

func (GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretAwsSecretsManager)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput() GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput {
	return i.ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput)
}

// GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayInput is an input type that accepts GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray and GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayInput` via:
//
//	GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray{ GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs{...} }
type GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput() GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput
	ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput
}

type GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray []GetListInstanceDataSourceExternalSecretAwsSecretsManagerInput

func (GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretAwsSecretsManager)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput() GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput {
	return i.ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput)
}

type GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretAwsSecretsManager)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput() GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput {
	return o
}

// The key name for the password.
func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput) PasswordKeyName() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretAwsSecretsManager) string { return v.PasswordKeyName }).(pulumi.StringOutput)
}

// The secret name to store the password.
func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput) SecretName() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretAwsSecretsManager) string { return v.SecretName }).(pulumi.StringOutput)
}

type GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretAwsSecretsManager)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput() GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput) ToGetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput) Index(i pulumi.IntInput) GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstanceDataSourceExternalSecretAwsSecretsManager {
		return vs[0].([]GetListInstanceDataSourceExternalSecretAwsSecretsManager)[vs[1].(int)]
	}).(GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput)
}

type GetListInstanceDataSourceExternalSecretGcpSecretManager struct {
	// The secret name should be like "projects/{project-id}/secrets/{secret-id}".
	SecretName string `pulumi:"secretName"`
}

// GetListInstanceDataSourceExternalSecretGcpSecretManagerInput is an input type that accepts GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs and GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretGcpSecretManagerInput` via:
//
//	GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs{...}
type GetListInstanceDataSourceExternalSecretGcpSecretManagerInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutput() GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput
	ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput
}

type GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs struct {
	// The secret name should be like "projects/{project-id}/secrets/{secret-id}".
	SecretName pulumi.StringInput `pulumi:"secretName"`
}

func (GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretGcpSecretManager)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutput() GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput {
	return i.ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput)
}

// GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayInput is an input type that accepts GetListInstanceDataSourceExternalSecretGcpSecretManagerArray and GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayInput` via:
//
//	GetListInstanceDataSourceExternalSecretGcpSecretManagerArray{ GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs{...} }
type GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput() GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput
	ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput
}

type GetListInstanceDataSourceExternalSecretGcpSecretManagerArray []GetListInstanceDataSourceExternalSecretGcpSecretManagerInput

func (GetListInstanceDataSourceExternalSecretGcpSecretManagerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretGcpSecretManager)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretGcpSecretManagerArray) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput() GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput {
	return i.ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretGcpSecretManagerArray) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput)
}

type GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretGcpSecretManager)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutput() GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput {
	return o
}

// The secret name should be like "projects/{project-id}/secrets/{secret-id}".
func (o GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput) SecretName() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretGcpSecretManager) string { return v.SecretName }).(pulumi.StringOutput)
}

type GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretGcpSecretManager)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput() GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput) ToGetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput) Index(i pulumi.IntInput) GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstanceDataSourceExternalSecretGcpSecretManager {
		return vs[0].([]GetListInstanceDataSourceExternalSecretGcpSecretManager)[vs[1].(int)]
	}).(GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput)
}

type GetListInstanceDataSourceExternalSecretVault struct {
	// The Vault app role to get the password.
	AppRoles []GetListInstanceDataSourceExternalSecretVaultAppRole `pulumi:"appRoles"`
	// The name for secret engine.
	EngineName string `pulumi:"engineName"`
	// The key name for the password.
	PasswordKeyName string `pulumi:"passwordKeyName"`
	// The secret name in the engine to store the password.
	SecretName string `pulumi:"secretName"`
	Token      string `pulumi:"token"`
	// The Vault URL.
	Url string `pulumi:"url"`
}

// GetListInstanceDataSourceExternalSecretVaultInput is an input type that accepts GetListInstanceDataSourceExternalSecretVaultArgs and GetListInstanceDataSourceExternalSecretVaultOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretVaultInput` via:
//
//	GetListInstanceDataSourceExternalSecretVaultArgs{...}
type GetListInstanceDataSourceExternalSecretVaultInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretVaultOutput() GetListInstanceDataSourceExternalSecretVaultOutput
	ToGetListInstanceDataSourceExternalSecretVaultOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretVaultOutput
}

type GetListInstanceDataSourceExternalSecretVaultArgs struct {
	// The Vault app role to get the password.
	AppRoles GetListInstanceDataSourceExternalSecretVaultAppRoleArrayInput `pulumi:"appRoles"`
	// The name for secret engine.
	EngineName pulumi.StringInput `pulumi:"engineName"`
	// The key name for the password.
	PasswordKeyName pulumi.StringInput `pulumi:"passwordKeyName"`
	// The secret name in the engine to store the password.
	SecretName pulumi.StringInput `pulumi:"secretName"`
	Token      pulumi.StringInput `pulumi:"token"`
	// The Vault URL.
	Url pulumi.StringInput `pulumi:"url"`
}

func (GetListInstanceDataSourceExternalSecretVaultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVault)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretVaultArgs) ToGetListInstanceDataSourceExternalSecretVaultOutput() GetListInstanceDataSourceExternalSecretVaultOutput {
	return i.ToGetListInstanceDataSourceExternalSecretVaultOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretVaultArgs) ToGetListInstanceDataSourceExternalSecretVaultOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretVaultOutput)
}

// GetListInstanceDataSourceExternalSecretVaultArrayInput is an input type that accepts GetListInstanceDataSourceExternalSecretVaultArray and GetListInstanceDataSourceExternalSecretVaultArrayOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretVaultArrayInput` via:
//
//	GetListInstanceDataSourceExternalSecretVaultArray{ GetListInstanceDataSourceExternalSecretVaultArgs{...} }
type GetListInstanceDataSourceExternalSecretVaultArrayInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretVaultArrayOutput() GetListInstanceDataSourceExternalSecretVaultArrayOutput
	ToGetListInstanceDataSourceExternalSecretVaultArrayOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretVaultArrayOutput
}

type GetListInstanceDataSourceExternalSecretVaultArray []GetListInstanceDataSourceExternalSecretVaultInput

func (GetListInstanceDataSourceExternalSecretVaultArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretVault)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretVaultArray) ToGetListInstanceDataSourceExternalSecretVaultArrayOutput() GetListInstanceDataSourceExternalSecretVaultArrayOutput {
	return i.ToGetListInstanceDataSourceExternalSecretVaultArrayOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretVaultArray) ToGetListInstanceDataSourceExternalSecretVaultArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretVaultArrayOutput)
}

type GetListInstanceDataSourceExternalSecretVaultOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretVaultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVault)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretVaultOutput) ToGetListInstanceDataSourceExternalSecretVaultOutput() GetListInstanceDataSourceExternalSecretVaultOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretVaultOutput) ToGetListInstanceDataSourceExternalSecretVaultOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultOutput {
	return o
}

// The Vault app role to get the password.
func (o GetListInstanceDataSourceExternalSecretVaultOutput) AppRoles() GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVault) []GetListInstanceDataSourceExternalSecretVaultAppRole {
		return v.AppRoles
	}).(GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput)
}

// The name for secret engine.
func (o GetListInstanceDataSourceExternalSecretVaultOutput) EngineName() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVault) string { return v.EngineName }).(pulumi.StringOutput)
}

// The key name for the password.
func (o GetListInstanceDataSourceExternalSecretVaultOutput) PasswordKeyName() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVault) string { return v.PasswordKeyName }).(pulumi.StringOutput)
}

// The secret name in the engine to store the password.
func (o GetListInstanceDataSourceExternalSecretVaultOutput) SecretName() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVault) string { return v.SecretName }).(pulumi.StringOutput)
}

func (o GetListInstanceDataSourceExternalSecretVaultOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVault) string { return v.Token }).(pulumi.StringOutput)
}

// The Vault URL.
func (o GetListInstanceDataSourceExternalSecretVaultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVault) string { return v.Url }).(pulumi.StringOutput)
}

type GetListInstanceDataSourceExternalSecretVaultArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretVaultArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretVault)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretVaultArrayOutput) ToGetListInstanceDataSourceExternalSecretVaultArrayOutput() GetListInstanceDataSourceExternalSecretVaultArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretVaultArrayOutput) ToGetListInstanceDataSourceExternalSecretVaultArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretVaultArrayOutput) Index(i pulumi.IntInput) GetListInstanceDataSourceExternalSecretVaultOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstanceDataSourceExternalSecretVault {
		return vs[0].([]GetListInstanceDataSourceExternalSecretVault)[vs[1].(int)]
	}).(GetListInstanceDataSourceExternalSecretVaultOutput)
}

type GetListInstanceDataSourceExternalSecretVaultAppRole struct {
	// The app role id.
	RoleId string `pulumi:"roleId"`
	// The secret id for the role without ttl.
	Secret string `pulumi:"secret"`
	// The secret id type, can be PLAIN (plain text for the secret) or ENVIRONMENT (envirionment name for the secret).
	SecretType string `pulumi:"secretType"`
}

// GetListInstanceDataSourceExternalSecretVaultAppRoleInput is an input type that accepts GetListInstanceDataSourceExternalSecretVaultAppRoleArgs and GetListInstanceDataSourceExternalSecretVaultAppRoleOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretVaultAppRoleInput` via:
//
//	GetListInstanceDataSourceExternalSecretVaultAppRoleArgs{...}
type GetListInstanceDataSourceExternalSecretVaultAppRoleInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutput() GetListInstanceDataSourceExternalSecretVaultAppRoleOutput
	ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretVaultAppRoleOutput
}

type GetListInstanceDataSourceExternalSecretVaultAppRoleArgs struct {
	// The app role id.
	RoleId pulumi.StringInput `pulumi:"roleId"`
	// The secret id for the role without ttl.
	Secret pulumi.StringInput `pulumi:"secret"`
	// The secret id type, can be PLAIN (plain text for the secret) or ENVIRONMENT (envirionment name for the secret).
	SecretType pulumi.StringInput `pulumi:"secretType"`
}

func (GetListInstanceDataSourceExternalSecretVaultAppRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVaultAppRole)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretVaultAppRoleArgs) ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutput() GetListInstanceDataSourceExternalSecretVaultAppRoleOutput {
	return i.ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretVaultAppRoleArgs) ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultAppRoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretVaultAppRoleOutput)
}

// GetListInstanceDataSourceExternalSecretVaultAppRoleArrayInput is an input type that accepts GetListInstanceDataSourceExternalSecretVaultAppRoleArray and GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput values.
// You can construct a concrete instance of `GetListInstanceDataSourceExternalSecretVaultAppRoleArrayInput` via:
//
//	GetListInstanceDataSourceExternalSecretVaultAppRoleArray{ GetListInstanceDataSourceExternalSecretVaultAppRoleArgs{...} }
type GetListInstanceDataSourceExternalSecretVaultAppRoleArrayInput interface {
	pulumi.Input

	ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput() GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput
	ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutputWithContext(context.Context) GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput
}

type GetListInstanceDataSourceExternalSecretVaultAppRoleArray []GetListInstanceDataSourceExternalSecretVaultAppRoleInput

func (GetListInstanceDataSourceExternalSecretVaultAppRoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretVaultAppRole)(nil)).Elem()
}

func (i GetListInstanceDataSourceExternalSecretVaultAppRoleArray) ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput() GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput {
	return i.ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutputWithContext(context.Background())
}

func (i GetListInstanceDataSourceExternalSecretVaultAppRoleArray) ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput)
}

type GetListInstanceDataSourceExternalSecretVaultAppRoleOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretVaultAppRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVaultAppRole)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretVaultAppRoleOutput) ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutput() GetListInstanceDataSourceExternalSecretVaultAppRoleOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretVaultAppRoleOutput) ToGetListInstanceDataSourceExternalSecretVaultAppRoleOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultAppRoleOutput {
	return o
}

// The app role id.
func (o GetListInstanceDataSourceExternalSecretVaultAppRoleOutput) RoleId() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVaultAppRole) string { return v.RoleId }).(pulumi.StringOutput)
}

// The secret id for the role without ttl.
func (o GetListInstanceDataSourceExternalSecretVaultAppRoleOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVaultAppRole) string { return v.Secret }).(pulumi.StringOutput)
}

// The secret id type, can be PLAIN (plain text for the secret) or ENVIRONMENT (envirionment name for the secret).
func (o GetListInstanceDataSourceExternalSecretVaultAppRoleOutput) SecretType() pulumi.StringOutput {
	return o.ApplyT(func(v GetListInstanceDataSourceExternalSecretVaultAppRole) string { return v.SecretType }).(pulumi.StringOutput)
}

type GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput struct{ *pulumi.OutputState }

func (GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetListInstanceDataSourceExternalSecretVaultAppRole)(nil)).Elem()
}

func (o GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput) ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput() GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput) ToGetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutputWithContext(ctx context.Context) GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput {
	return o
}

func (o GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput) Index(i pulumi.IntInput) GetListInstanceDataSourceExternalSecretVaultAppRoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetListInstanceDataSourceExternalSecretVaultAppRole {
		return vs[0].([]GetListInstanceDataSourceExternalSecretVaultAppRole)[vs[1].(int)]
	}).(GetListInstanceDataSourceExternalSecretVaultAppRoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceInput)(nil)).Elem(), GetListInstanceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceArrayInput)(nil)).Elem(), GetListInstanceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceInput)(nil)).Elem(), GetListInstanceDataSourceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceArrayInput)(nil)).Elem(), GetListInstanceDataSourceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretArrayInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretAwsSecretsManagerInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretAwsSecretsManagerArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretAwsSecretsManagerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretGcpSecretManagerInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretGcpSecretManagerArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretGcpSecretManagerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVaultInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretVaultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVaultArrayInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretVaultArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVaultAppRoleInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretVaultAppRoleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetListInstanceDataSourceExternalSecretVaultAppRoleArrayInput)(nil)).Elem(), GetListInstanceDataSourceExternalSecretVaultAppRoleArray{})
	pulumi.RegisterOutputType(GetListInstanceOutput{})
	pulumi.RegisterOutputType(GetListInstanceArrayOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceArrayOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretArrayOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretAwsSecretsManagerOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretAwsSecretsManagerArrayOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretGcpSecretManagerOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretGcpSecretManagerArrayOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretVaultOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretVaultArrayOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretVaultAppRoleOutput{})
	pulumi.RegisterOutputType(GetListInstanceDataSourceExternalSecretVaultAppRoleArrayOutput{})
}
