# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetListRoleResult',
]

@pulumi.output_type
class GetListRoleResult(dict):
    def __init__(__self__, *,
                 description: _builtins.str,
                 name: _builtins.str,
                 permissions: Sequence[_builtins.str],
                 resource_id: _builtins.str,
                 title: _builtins.str,
                 type: _builtins.str):
        """
        :param _builtins.str description: The role description.
        :param _builtins.str name: The role full name in roles/{resource id} format.
        :param Sequence[_builtins.str] permissions: The role permissions.
        :param _builtins.str resource_id: The role unique resource id.
        :param _builtins.str title: The role title.
        :param _builtins.str type: The role type.
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "permissions", permissions)
        pulumi.set(__self__, "resource_id", resource_id)
        pulumi.set(__self__, "title", title)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        The role description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The role full name in roles/{resource id} format.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> Sequence[_builtins.str]:
        """
        The role permissions.
        """
        return pulumi.get(self, "permissions")

    @_builtins.property
    @pulumi.getter(name="resourceId")
    def resource_id(self) -> _builtins.str:
        """
        The role unique resource id.
        """
        return pulumi.get(self, "resource_id")

    @_builtins.property
    @pulumi.getter
    def title(self) -> _builtins.str:
        """
        The role title.
        """
        return pulumi.get(self, "title")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        The role type.
        """
        return pulumi.get(self, "type")


