// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * The role data source list.
 */
export function getList(opts?: pulumi.InvokeOptions): Promise<GetListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytebase:Role/getList:getList", {
    }, opts);
}

/**
 * A collection of values returned by getList.
 */
export interface GetListResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly roles: outputs.Role.GetListRole[];
}
/**
 * The role data source list.
 */
export function getListOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytebase:Role/getList:getList", {
    }, opts);
}
