// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package databasegroup

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/wawilow/pulumi-bytebase/sdk/go/bytebase/internal"
)

// The database group data source list.
func GetList(ctx *pulumi.Context, args *GetListArgs, opts ...pulumi.InvokeOption) (*GetListResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetListResult
	err := ctx.Invoke("bytebase:DatabaseGroup/getList:getList", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getList.
type GetListArgs struct {
	// The project fullname in projects/{id} format.
	Project string `pulumi:"project"`
}

// A collection of values returned by getList.
type GetListResult struct {
	DatabaseGroups []GetListDatabaseGroup `pulumi:"databaseGroups"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The project fullname in projects/{id} format.
	Project string `pulumi:"project"`
}

func GetListOutput(ctx *pulumi.Context, args GetListOutputArgs, opts ...pulumi.InvokeOption) GetListResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetListResultOutput, error) {
			args := v.(GetListArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("bytebase:DatabaseGroup/getList:getList", args, GetListResultOutput{}, options).(GetListResultOutput), nil
		}).(GetListResultOutput)
}

// A collection of arguments for invoking getList.
type GetListOutputArgs struct {
	// The project fullname in projects/{id} format.
	Project pulumi.StringInput `pulumi:"project"`
}

func (GetListOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListArgs)(nil)).Elem()
}

// A collection of values returned by getList.
type GetListResultOutput struct{ *pulumi.OutputState }

func (GetListResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetListResult)(nil)).Elem()
}

func (o GetListResultOutput) ToGetListResultOutput() GetListResultOutput {
	return o
}

func (o GetListResultOutput) ToGetListResultOutputWithContext(ctx context.Context) GetListResultOutput {
	return o
}

func (o GetListResultOutput) DatabaseGroups() GetListDatabaseGroupArrayOutput {
	return o.ApplyT(func(v GetListResult) []GetListDatabaseGroup { return v.DatabaseGroups }).(GetListDatabaseGroupArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetListResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetListResult) string { return v.Id }).(pulumi.StringOutput)
}

// The project fullname in projects/{id} format.
func (o GetListResultOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v GetListResult) string { return v.Project }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetListResultOutput{})
}
