// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("bytebase");

/**
 * The Bytebase service account email. If not provided in the configuration, you must set the `BYTEBASE_SERVICE_ACCOUNT`
 * variable in the environment.
 */
export declare const serviceAccount: string | undefined;
Object.defineProperty(exports, "serviceAccount", {
    get() {
        return __config.get("serviceAccount");
    },
    enumerable: true,
});

/**
 * The Bytebase service account key. If not provided in the configuration, you must set the `BYTEBASE_SERVICE_KEY` variable
 * in the environment.
 */
export declare const serviceKey: string | undefined;
Object.defineProperty(exports, "serviceKey", {
    get() {
        return __config.get("serviceKey");
    },
    enumerable: true,
});

/**
 * The external URL for your Bytebase server. If not provided in the configuration, you must set the `BYTEBASE_URL`
 * variable in the environment.
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

