// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * The database group data source list.
 */
export function getList(args: GetListArgs, opts?: pulumi.InvokeOptions): Promise<GetListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytebase:DatabaseGroup/getList:getList", {
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getList.
 */
export interface GetListArgs {
    /**
     * The project fullname in projects/{id} format.
     */
    project: string;
}

/**
 * A collection of values returned by getList.
 */
export interface GetListResult {
    readonly databaseGroups: outputs.DatabaseGroup.GetListDatabaseGroup[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The project fullname in projects/{id} format.
     */
    readonly project: string;
}
/**
 * The database group data source list.
 */
export function getListOutput(args: GetListOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetListResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytebase:DatabaseGroup/getList:getList", {
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getList.
 */
export interface GetListOutputArgs {
    /**
     * The project fullname in projects/{id} format.
     */
    project: pulumi.Input<string>;
}
