// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * The IAM policy data source.
 */
export function getPolicy(args: GetPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytebase:Iam/getPolicy:getPolicy", {
        "iamPolicy": args.iamPolicy,
        "parent": args.parent,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyArgs {
    iamPolicy?: inputs.Iam.GetPolicyIamPolicy;
    /**
     * The IAM policy parent name for the policy, support "projects/{resource id}" or "workspaces/-"
     */
    parent: string;
}

/**
 * A collection of values returned by getPolicy.
 */
export interface GetPolicyResult {
    readonly iamPolicy: outputs.Iam.GetPolicyIamPolicy;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The IAM policy parent name for the policy, support "projects/{resource id}" or "workspaces/-"
     */
    readonly parent: string;
}
/**
 * The IAM policy data source.
 */
export function getPolicyOutput(args: GetPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytebase:Iam/getPolicy:getPolicy", {
        "iamPolicy": args.iamPolicy,
        "parent": args.parent,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyOutputArgs {
    iamPolicy?: pulumi.Input<inputs.Iam.GetPolicyIamPolicyArgs>;
    /**
     * The IAM policy parent name for the policy, support "projects/{resource id}" or "workspaces/-"
     */
    parent: pulumi.Input<string>;
}
