# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetListDatabaseResult',
]

@pulumi.output_type
class GetListDatabaseResult(dict):
    def __init__(__self__, *,
                 environment: _builtins.str,
                 labels: Mapping[str, _builtins.str],
                 name: _builtins.str,
                 project: _builtins.str,
                 schema_version: _builtins.str,
                 state: _builtins.str,
                 successful_sync_time: _builtins.str):
        """
        :param _builtins.str environment: The database environment, will follow the instance environment by default
        :param Mapping[str, _builtins.str] labels: The deployment and policy control labels.
        :param _builtins.str name: The database full name in instances/{instance}/databases/{database} format
        :param _builtins.str project: The project full name for the database in projects/{project} format.
        :param _builtins.str schema_version: The version of database schema.
        :param _builtins.str state: The existence of a database.
        :param _builtins.str successful_sync_time: The latest synchronization time.
        """
        pulumi.set(__self__, "environment", environment)
        pulumi.set(__self__, "labels", labels)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "schema_version", schema_version)
        pulumi.set(__self__, "state", state)
        pulumi.set(__self__, "successful_sync_time", successful_sync_time)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> _builtins.str:
        """
        The database environment, will follow the instance environment by default
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Mapping[str, _builtins.str]:
        """
        The deployment and policy control labels.
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The database full name in instances/{instance}/databases/{database} format
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def project(self) -> _builtins.str:
        """
        The project full name for the database in projects/{project} format.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter(name="schemaVersion")
    def schema_version(self) -> _builtins.str:
        """
        The version of database schema.
        """
        return pulumi.get(self, "schema_version")

    @_builtins.property
    @pulumi.getter
    def state(self) -> _builtins.str:
        """
        The existence of a database.
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter(name="successfulSyncTime")
    def successful_sync_time(self) -> _builtins.str:
        """
        The latest synchronization time.
        """
        return pulumi.get(self, "successful_sync_time")


