// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The database data source.
 */
export function getDatabase(args: GetDatabaseArgs, opts?: pulumi.InvokeOptions): Promise<GetDatabaseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytebase:index/getDatabase:getDatabase", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDatabase.
 */
export interface GetDatabaseArgs {
    /**
     * The database full name in instances/{instance}/databases/{database} format
     */
    name: string;
}

/**
 * A collection of values returned by getDatabase.
 */
export interface GetDatabaseResult {
    /**
     * The databases catalog.
     */
    readonly catalogs: outputs.GetDatabaseCatalog[];
    /**
     * The database environment, will follow the instance environment by default
     */
    readonly environment: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The deployment and policy control labels.
     */
    readonly labels: {[key: string]: string};
    /**
     * The database full name in instances/{instance}/databases/{database} format
     */
    readonly name: string;
    /**
     * The project full name for the database in projects/{project} format.
     */
    readonly project: string;
    /**
     * The version of database schema.
     */
    readonly schemaVersion: string;
    /**
     * The existence of a database.
     */
    readonly state: string;
    /**
     * The latest synchronization time.
     */
    readonly successfulSyncTime: string;
}
/**
 * The database data source.
 */
export function getDatabaseOutput(args: GetDatabaseOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDatabaseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytebase:index/getDatabase:getDatabase", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDatabase.
 */
export interface GetDatabaseOutputArgs {
    /**
     * The database full name in instances/{instance}/databases/{database} format
     */
    name: pulumi.Input<string>;
}
