// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The policy data source.
 */
export function getPolicy(args: GetPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bytebase:index/getPolicy:getPolicy", {
        "dataSourceQueryPolicy": args.dataSourceQueryPolicy,
        "disableCopyDataPolicy": args.disableCopyDataPolicy,
        "globalMaskingPolicy": args.globalMaskingPolicy,
        "maskingExceptionPolicy": args.maskingExceptionPolicy,
        "parent": args.parent,
        "rolloutPolicy": args.rolloutPolicy,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyArgs {
    /**
     * Restrict querying admin data sources
     */
    dataSourceQueryPolicy?: inputs.GetPolicyDataSourceQueryPolicy;
    /**
     * Restrict data copying in SQL Editor (Admins/DBAs allowed)
     */
    disableCopyDataPolicy?: inputs.GetPolicyDisableCopyDataPolicy;
    globalMaskingPolicy?: inputs.GetPolicyGlobalMaskingPolicy;
    maskingExceptionPolicy?: inputs.GetPolicyMaskingExceptionPolicy;
    /**
     * The policy parent name for the policy, support projects/{resource id}, environments/{resource id}, instances/{resource id}, or instances/{resource id}/databases/{database name}
     */
    parent: string;
    /**
     * Control issue rollout. Learn more: https://docs.bytebase.com/administration/environment-policy/rollout-policy
     */
    rolloutPolicy?: inputs.GetPolicyRolloutPolicy;
    /**
     * The policy type.
     */
    type: string;
}

/**
 * A collection of values returned by getPolicy.
 */
export interface GetPolicyResult {
    /**
     * Restrict querying admin data sources
     */
    readonly dataSourceQueryPolicy: outputs.GetPolicyDataSourceQueryPolicy;
    /**
     * Restrict data copying in SQL Editor (Admins/DBAs allowed)
     */
    readonly disableCopyDataPolicy: outputs.GetPolicyDisableCopyDataPolicy;
    /**
     * Decide if the policy is enforced.
     */
    readonly enforce: boolean;
    readonly globalMaskingPolicy: outputs.GetPolicyGlobalMaskingPolicy;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Decide if the policy should inherit from the parent.
     */
    readonly inheritFromParent: boolean;
    readonly maskingExceptionPolicy: outputs.GetPolicyMaskingExceptionPolicy;
    /**
     * The policy full name
     */
    readonly name: string;
    /**
     * The policy parent name for the policy, support projects/{resource id}, environments/{resource id}, instances/{resource id}, or instances/{resource id}/databases/{database name}
     */
    readonly parent: string;
    /**
     * Control issue rollout. Learn more: https://docs.bytebase.com/administration/environment-policy/rollout-policy
     */
    readonly rolloutPolicy: outputs.GetPolicyRolloutPolicy;
    /**
     * The policy type.
     */
    readonly type: string;
}
/**
 * The policy data source.
 */
export function getPolicyOutput(args: GetPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bytebase:index/getPolicy:getPolicy", {
        "dataSourceQueryPolicy": args.dataSourceQueryPolicy,
        "disableCopyDataPolicy": args.disableCopyDataPolicy,
        "globalMaskingPolicy": args.globalMaskingPolicy,
        "maskingExceptionPolicy": args.maskingExceptionPolicy,
        "parent": args.parent,
        "rolloutPolicy": args.rolloutPolicy,
        "type": args.type,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyOutputArgs {
    /**
     * Restrict querying admin data sources
     */
    dataSourceQueryPolicy?: pulumi.Input<inputs.GetPolicyDataSourceQueryPolicyArgs>;
    /**
     * Restrict data copying in SQL Editor (Admins/DBAs allowed)
     */
    disableCopyDataPolicy?: pulumi.Input<inputs.GetPolicyDisableCopyDataPolicyArgs>;
    globalMaskingPolicy?: pulumi.Input<inputs.GetPolicyGlobalMaskingPolicyArgs>;
    maskingExceptionPolicy?: pulumi.Input<inputs.GetPolicyMaskingExceptionPolicyArgs>;
    /**
     * The policy parent name for the policy, support projects/{resource id}, environments/{resource id}, instances/{resource id}, or instances/{resource id}/databases/{database name}
     */
    parent: pulumi.Input<string>;
    /**
     * Control issue rollout. Learn more: https://docs.bytebase.com/administration/environment-policy/rollout-policy
     */
    rolloutPolicy?: pulumi.Input<inputs.GetPolicyRolloutPolicyArgs>;
    /**
     * The policy type.
     */
    type: pulumi.Input<string>;
}
