// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The user resource.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bytebase:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * The user email.
     */
    public readonly email!: pulumi.Output<string>;
    /**
     * The user last change password time.
     */
    public /*out*/ readonly lastChangePasswordTime!: pulumi.Output<string>;
    /**
     * The user last login time.
     */
    public /*out*/ readonly lastLoginTime!: pulumi.Output<string>;
    /**
     * The mfaEnabled flag means if the user has enabled MFA.
     */
    public /*out*/ readonly mfaEnabled!: pulumi.Output<boolean>;
    /**
     * The user name in users/{user id or email} format.
     */
    public /*out*/ readonly name!: pulumi.Output<string>;
    /**
     * The user login password.
     */
    public readonly password!: pulumi.Output<string | undefined>;
    /**
     * The user phone.
     */
    public readonly phone!: pulumi.Output<string>;
    /**
     * The service key for service account.
     */
    public /*out*/ readonly serviceKey!: pulumi.Output<string>;
    /**
     * Source means where the user comes from. For now we support Entra ID SCIM sync, so the source could be Entra ID.
     */
    public /*out*/ readonly source!: pulumi.Output<string>;
    /**
     * The user is deleted or not.
     */
    public /*out*/ readonly state!: pulumi.Output<string>;
    /**
     * The user title.
     */
    public readonly title!: pulumi.Output<string>;
    /**
     * The user type, should be USER or SERVICE_ACCOUNT. Cannot change after creation.
     */
    public readonly type!: pulumi.Output<string | undefined>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as UserState | undefined;
            resourceInputs["email"] = state ? state.email : undefined;
            resourceInputs["lastChangePasswordTime"] = state ? state.lastChangePasswordTime : undefined;
            resourceInputs["lastLoginTime"] = state ? state.lastLoginTime : undefined;
            resourceInputs["mfaEnabled"] = state ? state.mfaEnabled : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["phone"] = state ? state.phone : undefined;
            resourceInputs["serviceKey"] = state ? state.serviceKey : undefined;
            resourceInputs["source"] = state ? state.source : undefined;
            resourceInputs["state"] = state ? state.state : undefined;
            resourceInputs["title"] = state ? state.title : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if ((!args || args.email === undefined) && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if ((!args || args.title === undefined) && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            resourceInputs["email"] = args ? args.email : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["phone"] = args ? args.phone : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["lastChangePasswordTime"] = undefined /*out*/;
            resourceInputs["lastLoginTime"] = undefined /*out*/;
            resourceInputs["mfaEnabled"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["serviceKey"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * The user email.
     */
    email?: pulumi.Input<string>;
    /**
     * The user last change password time.
     */
    lastChangePasswordTime?: pulumi.Input<string>;
    /**
     * The user last login time.
     */
    lastLoginTime?: pulumi.Input<string>;
    /**
     * The mfaEnabled flag means if the user has enabled MFA.
     */
    mfaEnabled?: pulumi.Input<boolean>;
    /**
     * The user name in users/{user id or email} format.
     */
    name?: pulumi.Input<string>;
    /**
     * The user login password.
     */
    password?: pulumi.Input<string>;
    /**
     * The user phone.
     */
    phone?: pulumi.Input<string>;
    /**
     * The service key for service account.
     */
    serviceKey?: pulumi.Input<string>;
    /**
     * Source means where the user comes from. For now we support Entra ID SCIM sync, so the source could be Entra ID.
     */
    source?: pulumi.Input<string>;
    /**
     * The user is deleted or not.
     */
    state?: pulumi.Input<string>;
    /**
     * The user title.
     */
    title?: pulumi.Input<string>;
    /**
     * The user type, should be USER or SERVICE_ACCOUNT. Cannot change after creation.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * The user email.
     */
    email: pulumi.Input<string>;
    /**
     * The user login password.
     */
    password?: pulumi.Input<string>;
    /**
     * The user phone.
     */
    phone?: pulumi.Input<string>;
    /**
     * The user title.
     */
    title: pulumi.Input<string>;
    /**
     * The user type, should be USER or SERVICE_ACCOUNT. Cannot change after creation.
     */
    type?: pulumi.Input<string>;
}
